# Configuration for attributing commits with emails to GitHub user profiles
# Used during codeowners generation.

# List the emails associated with the given username.
# The commits associated with these emails will be attributed to
# the username in this yaml map. Any number of emails may be listed.
attribution:
  nickytonline:
    - nick@nickyt.co
    - nick@opensauced.pizza
