name: "Assign issues with .take"

on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  take-issue:
    name: Disable take issue
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: take an issue
        uses: nickytonline/take-action@add-support-for-blocking-labels
        with:
          issueCurrentlyAssignedMessage: Thanks for being interested in this issue. It looks like this ticket is already assigned to a contributor.
          blockingLabels: "needs-triage,blocked"
          token: ${{ secrets.GITHUB_TOKEN }}
